apiVersion: v1
kind: Service
metadata:
  name: triton
  namespace: triton
  labels:
    app: triton
spec:
  selector:
    app: triton
  ports:
  - name: httpd
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: grpc
    protocol: TCP
    port: 8001
    targetPort: 8001
  - name: metrics
    protocol: TCP
    port: 8002
    targetPort: 8002
  type: LoadBalancer
