# https://gitlab.nrp-nautilus.io/raghsthebest/triton-server/-/blob/main/triton-inference-server-replicas.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
  namespace: triton

spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      # nodeName: k8s-gpu-2.ucsc.edu
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-GTX-1080-Ti
                      - NVIDIA-GeForce-GTX-2080-Ti
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - sdsu-rci
                      - ucm-fiona01.ucmerced.edu
      tolerations:
        - key: "nautilus.io/large-gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: triton
          image: nvcr.io/nvidia/tritonserver:22.12-py3
          # image: gitlab-registry.nrp-nautilus.io/raghsthebest/triton-server:21.06-py3
          command: ["bash", "-c"]
          args:
            [
              "git config --global --add safe.directory /triton/sonic-models && git -C /triton/sonic-models pull && tritonserver --model-repository=/triton/sonic-models/models --exit-on-error=false",
            ]
          stdin: true
          tty: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: grpc
              containerPort: 8001
              protocol: TCP
            - name: metrics
              containerPort: 8002
              protocol: TCP
          resources:
            limits:
              memory: 12Gi
              cpu: "4"
              nvidia.com/gpu: "2"
            requests:
              memory: 12Gi
              cpu: "4"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /triton
              name: triton-model-repository-central
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: triton-model-repository-central
          persistentVolumeClaim:
            claimName: triton-model-repository-central
