apiVersion: v1
kind: Pod
metadata:
  name: tritonpodi
  labels:
    app: triton
spec:
  containers:
  - name: container
    #image: gitlab-registry.nrp-nautilus.io/raghsthebest/mnist-graph-gan:latest
    image: gitlab-registry.nrp-nautilus.io/raghsthebest/triton-server:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      #  nvidia.com/gpu: "1"
        ephemeral-storage: 512Gi
      limits:
        memory: 4Gi
        cpu: "1"
      #  nvidia.com/gpu: "1"
        ephemeral-storage: 512Gi
    volumeMounts:
    - mountPath: /triton
      name: triton-model-repository-central
  restartPolicy: Never
  volumes:
    - name: triton-model-repository-central
      persistentVolumeClaim:
        claimName: triton-model-repository-central
