apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-model-repository-central
  namespace: triton
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
