samples_dir:
    "2018": ../eos/postprocessNov12_2018
    "2017": ../eos/postprocessNov12_2017
    "2016APV": ../eos/postprocessNov12_2016APV
    "2016": ../eos/postprocessNov12_2016

model_path: ../eos/model.onnx

samples:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data
    - WJetsQCD

regions_sel:

    ### no VBF and ggF categorization
    "SR199": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0)
    "SR1985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0)
    "SR198": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0)
    "SR1975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0)
    "SR197": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0)
    "SR1965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0)
    "SR196": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0)
    "SR1955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0)
    "SR195": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0)

    ### ggF all inclusive
    "SR1ggF99": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR1ggF985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR1ggF98": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR1ggF975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR1ggF97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR1ggF965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR1ggF96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR1ggF955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR1ggF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    ### VBF all inclusive
    "VBF99": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF98": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )

    ### ggF pt bins
    "SR1ggF985pt250to300": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "SR1ggF985pt300to450": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "SR1ggF985pt450toInf": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "SR1ggF98pt250to300": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "SR1ggF98pt300to450": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "SR1ggF98pt450toInf": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "SR1ggF975pt250to300": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "SR1ggF975pt300to450": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "SR1ggF975pt450toInf": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "SR1ggF97pt250to300": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "SR1ggF97pt300to450": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "SR1ggF97pt450toInf": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "SR1ggF965pt250to300": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "SR1ggF965pt300to450": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "SR1ggF965pt450toInf": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "SR1ggF96pt250to300": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "SR1ggF96pt300to450": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "SR1ggF96pt450toInf": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "SR1ggF955pt250to300": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "SR1ggF955pt300to450": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "SR1ggF955pt450toInf": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "SR1ggF95pt250to300": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "SR1ggF95pt300to450": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "SR1ggF95pt450toInf": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # potential SR2 ggF all inclusive
    "SR2ggF98and985": (fj_ParT_score_finetuned>0.98) & (fj_ParT_score_finetuned<0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF975and985": (fj_ParT_score_finetuned>0.975) & (fj_ParT_score_finetuned<0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF97and985": (fj_ParT_score_finetuned>0.97) & (fj_ParT_score_finetuned<0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF965and985": (fj_ParT_score_finetuned>0.965) & (fj_ParT_score_finetuned<0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF96and985": (fj_ParT_score_finetuned>0.96) & (fj_ParT_score_finetuned<0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    "SR2ggF975and98": (fj_ParT_score_finetuned>0.975) & (fj_ParT_score_finetuned<0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF97and98": (fj_ParT_score_finetuned>0.97) & (fj_ParT_score_finetuned<0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF965and98": (fj_ParT_score_finetuned>0.965) & (fj_ParT_score_finetuned<0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF96and98": (fj_ParT_score_finetuned>0.96) & (fj_ParT_score_finetuned<0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    "SR2ggF97and975": (fj_ParT_score_finetuned>0.97) & (fj_ParT_score_finetuned<0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF965and975": (fj_ParT_score_finetuned>0.965) & (fj_ParT_score_finetuned<0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "SR2ggF96and975": (fj_ParT_score_finetuned>0.96) & (fj_ParT_score_finetuned<0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
