samples:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    # - QCD
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - EWKvjets
    - Data
    # - DYJets
    # - WZQQ
    - WZQQorDYJets

regions_sel:
    ##### v21
    "VBF92": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF919": (fj_ParT_score_finetuned>0.919) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF918": (fj_ParT_score_finetuned>0.918) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF917": (fj_ParT_score_finetuned>0.917) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF916": (fj_ParT_score_finetuned>0.916) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF915": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF914": (fj_ParT_score_finetuned>0.914) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF913": (fj_ParT_score_finetuned>0.913) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF912": (fj_ParT_score_finetuned>0.912) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF911": (fj_ParT_score_finetuned>0.911) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF91": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )

    "ggF928pt250to300": (fj_ParT_score_finetuned>0.928) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF928pt300to450": (fj_ParT_score_finetuned>0.928) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF928pt450toInf": (fj_ParT_score_finetuned>0.928) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF927pt250to300": (fj_ParT_score_finetuned>0.927) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF927pt300to450": (fj_ParT_score_finetuned>0.927) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF927pt450toInf": (fj_ParT_score_finetuned>0.927) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF926pt250to300": (fj_ParT_score_finetuned>0.926) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF926pt300to450": (fj_ParT_score_finetuned>0.926) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF926pt450toInf": (fj_ParT_score_finetuned>0.926) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)
    
    "ggF925pt250to300": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF925pt300to450": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF925pt450toInf": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF924pt250to300": (fj_ParT_score_finetuned>0.924) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF924pt300to450": (fj_ParT_score_finetuned>0.924) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF924pt450toInf": (fj_ParT_score_finetuned>0.924) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF923pt250to300": (fj_ParT_score_finetuned>0.923) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF923pt300to450": (fj_ParT_score_finetuned>0.923) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF923pt450toInf": (fj_ParT_score_finetuned>0.923) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)            

    "ggF922pt250to300": (fj_ParT_score_finetuned>0.922) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF922pt300to450": (fj_ParT_score_finetuned>0.922) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF922pt450toInf": (fj_ParT_score_finetuned>0.922) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF921pt250to300": (fj_ParT_score_finetuned>0.921) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF921pt300to450": (fj_ParT_score_finetuned>0.921) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF921pt450toInf": (fj_ParT_score_finetuned>0.921) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)    

    "ggF920pt250to300": (fj_ParT_score_finetuned>0.920) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF920pt300to450": (fj_ParT_score_finetuned>0.920) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF920pt450toInf": (fj_ParT_score_finetuned>0.920) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    ##### v20
    # "VBF94": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF935": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF93": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF925": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF92": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF915": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF91": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF905": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF90": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF895": (fj_ParT_score_finetuned>0.895) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF89": (fj_ParT_score_finetuned>0.89) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF885": (fj_ParT_score_finetuned>0.885) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF88": (fj_ParT_score_finetuned>0.88) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )


    # "ggF97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF945": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF94": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF935": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF93": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF925": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF92": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF915": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF91": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF905": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF90": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF895": (fj_ParT_score_finetuned>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF89": (fj_ParT_score_finetuned>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF885": (fj_ParT_score_finetuned>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF88": (fj_ParT_score_finetuned>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )    


    # "ggF95pt250to300": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF95pt300to450": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF95pt450toInf": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF945pt250to300": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF945pt300to450": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF945pt450toInf": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF94pt250to300": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF94pt300to450": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF94pt450toInf": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF935pt250to300": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF935pt300to450": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF935pt450toInf": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF93pt250to300": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF93pt300to450": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF93pt450toInf": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF925pt250to300": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF925pt300to450": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF925pt450toInf": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF92pt250to300": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF92pt300to450": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF92pt450toInf": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF915pt250to300": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF915pt300to450": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF915pt450toInf": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF91pt250to300": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF91pt300to450": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF91pt450toInf": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF905pt250to300": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF905pt300to450": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF905pt450toInf": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "ggF90pt250to300": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggF90pt300to450": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggF90pt450toInf": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)


    "WJetsCR": (fj_ParT_score_finetuned>0.750) & (fj_ParT_score_finetuned<0.91) & (n_bjets_T==0)
    "TopCR": (fj_ParT_score_finetuned>0.750) & (n_bjets_T>0)


samples_dir:
    "2018": ../eos/Feb9_2018
    "2017": ../eos/Feb9_2017
    "2016APV": ../eos/Feb9_2016APV
    "2016": ../eos/Feb9_2016

# model_path: ../eos/model.onnx
# model_path: ../eos/model_v35_12_14.onnx
model_path: ../eos/model_v35_26.onnx
