samples:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

regions_sel:
    passHigh: ( (fj_ParT_score_finetuned>0.97) ) # high purity signal region
    passMedium: ( (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.85) ) # medium purity signal region
    wjetsCR: ( (fj_ParT_score_finetuned<0.85) & (fj_ParT_score_finetuned>0.20) & (lep_met_mt>40))

    # fail: ( (fj_ParT_score_finetuned<0.20) & (n_bjets_T == 0) ) # qcd control region
    # wjetsCR: ( (fj_ParT_score_finetuned<0.85) & (fj_ParT_score_finetuned>0.20) & (n_bjets_L == 0) )
    # ttbarCR: ( (fj_ParT_score_finetuned<0.20) & (n_bjets_T > 0) )

lepiso_sel: # keys must match keys in regions_sel above; values are either [lepiso, lepisoinv]
    passHigh: lepiso
    passMedium: lepiso
    wjetsCR: lepiso

    # fail: lepisoinv
    # ttbarCR: lepiso

categories_sel:
    VBFpt200toinf: ( (mjj>1000) & (deta>3.5) )
    ggFpt200to300: ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    ggFpt300toinf: ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300)

samples_dir:
    "2018": ../eos/postprocessOct5_hidNeurons_2018
    "2017": ../eos/postprocessOct9_hidNeurons_2017
    "2016APV": ../eos/postprocessOct13_hidNeurons_2016APV
    "2016": ../eos/postprocessOct13_hidNeurons_2016

model_path: ../eos/model.onnx
