samples:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - QCD
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - EWKvjets
    - Data
    - WZQQorDYJets

regions_sel:
    ##### v20
    # "VBF": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )

    # "ggFpt250to300": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggFpt300to450": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggFpt450toInf": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "WJetsCR": (fj_ParT_score_finetuned>0.750) & (fj_ParT_score_finetuned<0.925) & (n_bjets_T==0)
    # "TopCR": (fj_ParT_score_finetuned>0.750) & (n_bjets_T>0)

    "ParTFinetuned90": (fj_ParT_score_finetuned>0.9) & (n_bjets_T==0)
    "ParTFinetuned905": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0)
    "ParTFinetuned91": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0)
    "ParTFinetuned915": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0)
    "ParTFinetuned92": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0)
    "ParTFinetuned925": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0)
    "ParTFinetuned93": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0)
    "ParTFinetuned935": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0)
    "ParTFinetuned94": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0)
    "ParTFinetuned945": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0)
    "ParTFinetuned95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0)
    "ParTFinetuned955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0)
    "ParTFinetuned96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0)
    "ParTFinetuned965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0)
    "ParTFinetuned97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0)
    "ParTFinetuned975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0)
    "ParTFinetuned98": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0)
    "ParTFinetuned985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0)
    "ParTFinetuned99": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0)

    "VBF90": (fj_ParT_score_finetuned>0.9) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF905": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF91": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF915": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF92": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF925": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF93": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF935": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF94": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF945": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF955": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF98": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF99": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )    

    "ggF90": (fj_ParT_score_finetuned>0.9) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF905": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF91": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF915": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF92": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF925": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF93": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF935": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF94": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF945": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF98": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF99": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )



samples_dir:
    "2018": ../eos/Feb9_2018
    "2017": ../eos/Feb9_2017
    "2016APV": ../eos/Feb9_2016APV
    "2016": ../eos/Feb9_2016


model_path: ../../weaver-core-dev/experiments_finetuning/v35_26/model.onnx
