samples:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - QCD
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - EWKvjets
    - Data
    # - DYJets
    # - WZQQ
    - WZQQorDYJets

regions_sel:
    ##### v20
    # "VBF": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )

    # "ggFpt250to300": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    # "ggFpt300to450": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "ggFpt450toInf": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    # "WJetsCR": (fj_ParT_score_finetuned>0.750) & (fj_ParT_score_finetuned<0.925) & (n_bjets_T==0)
    # "TopCR": (fj_ParT_score_finetuned>0.750) & (n_bjets_T>0)


    "ParT90": (fj_ParT_score>0.9)
    "ParT905": (fj_ParT_score>0.905)
    "ParT91": (fj_ParT_score>0.91)
    "ParT915": (fj_ParT_score>0.915)
    "ParT92": (fj_ParT_score>0.92)
    "ParT925": (fj_ParT_score>0.925)
    "ParT93": (fj_ParT_score>0.93)
    "ParT935": (fj_ParT_score>0.935)
    "ParT94": (fj_ParT_score>0.94)
    "ParT945": (fj_ParT_score>0.945)
    "ParT95": (fj_ParT_score>0.95)
    "ParT955": (fj_ParT_score>0.955)
    "ParT96": (fj_ParT_score>0.96)
    "ParT965": (fj_ParT_score>0.965)
    "ParT97": (fj_ParT_score>0.97)
    "ParT975": (fj_ParT_score>0.975)
    "ParT98": (fj_ParT_score>0.98)
    "ParT985": (fj_ParT_score>0.985)
    "ParT99": (fj_ParT_score>0.99)
    "ParT995": (fj_ParT_score>0.995)
    "ParT999": (fj_ParT_score>0.999)
    "ParT9995": (fj_ParT_score>0.9995)
    "ParT9999": (fj_ParT_score>0.9999)

    "ParTFinetuned90": (fj_ParT_score_finetuned>0.9)
    "ParTFinetuned905": (fj_ParT_score_finetuned>0.905)
    "ParTFinetuned91": (fj_ParT_score_finetuned>0.91)
    "ParTFinetuned915": (fj_ParT_score_finetuned>0.915)
    "ParTFinetuned92": (fj_ParT_score_finetuned>0.92)
    "ParTFinetuned925": (fj_ParT_score_finetuned>0.925)
    "ParTFinetuned93": (fj_ParT_score_finetuned>0.93)
    "ParTFinetuned935": (fj_ParT_score_finetuned>0.935)
    "ParTFinetuned94": (fj_ParT_score_finetuned>0.94)
    "ParTFinetuned945": (fj_ParT_score_finetuned>0.945)
    "ParTFinetuned95": (fj_ParT_score_finetuned>0.95)
    "ParTFinetuned955": (fj_ParT_score_finetuned>0.955)
    "ParTFinetuned96": (fj_ParT_score_finetuned>0.96)
    "ParTFinetuned965": (fj_ParT_score_finetuned>0.965)
    "ParTFinetuned97": (fj_ParT_score_finetuned>0.97)
    "ParTFinetuned975": (fj_ParT_score_finetuned>0.975)
    "ParTFinetuned98": (fj_ParT_score_finetuned>0.98)
    "ParTFinetuned985": (fj_ParT_score_finetuned>0.985)
    "ParTFinetuned99": (fj_ParT_score_finetuned>0.99)


samples_dir:
    "2018": ../eos/Feb9_2018
    "2017": ../eos/Feb9_2017
    "2016APV": ../eos/Feb9_2016APV
    "2016": ../eos/Feb9_2016

# model_path: ../eos/model.onnx
model_path: ../eos/model_v35_26.onnx
