samples:
    - ggF
    - VBF
    - WH
    - ZH
    - ttH
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - EWKvjets
    - DYJets
    - WZQQ
    - Data

regions_sel:
    "WJetsCR": (THWW>0.75) & (THWW<0.9) & (n_bjets_T==0) & (rec_higgs_pt>250)
    "TopCR": (THWW>0.75) & (n_bjets_T>0) & (rec_higgs_pt>250)

    # check mjj and deta
    "VBF90and500and20": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF90and500and25": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.5) ) & (rec_higgs_pt>250)
    "VBF90and500and30": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>500) & (deta>3.0) ) & (rec_higgs_pt>250)
    "VBF90and500and35": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>500) & (deta>3.5) ) & (rec_higgs_pt>250)

    "VBF90and750and20": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>750) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF90and750and25": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>750) & (deta>2.5) ) & (rec_higgs_pt>250)
    "VBF90and750and30": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>750) & (deta>3.0) ) & (rec_higgs_pt>250)
    "VBF90and750and35": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>750) & (deta>3.5) ) & (rec_higgs_pt>250)

    "VBF90and1000and20": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>1000) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF90and1000and25": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>1000) & (deta>2.5) ) & (rec_higgs_pt>250)
    "VBF90and1000and30": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.0) ) & (rec_higgs_pt>250)
    "VBF90and1000and35": (THWW>0.9) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)

    "ggF90and500and20": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF90and500and25": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.5) ) & (rec_higgs_pt>250)
    "ggF90and500and30": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<500) | (deta<3.0) ) & (rec_higgs_pt>250)
    "ggF90and500and35": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<500) | (deta<3.5) ) & (rec_higgs_pt>250)

    "ggF90and750and20": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<750) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF90and750and25": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<750) | (deta<2.5) ) & (rec_higgs_pt>250)
    "ggF90and750and30": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<750) | (deta<3.0) ) & (rec_higgs_pt>250)
    "ggF90and750and35": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<750) | (deta<3.5) ) & (rec_higgs_pt>250)

    "ggF90and1000and20": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<1000) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF90and1000and25": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<1000) | (deta<2.5) ) & (rec_higgs_pt>250)
    "ggF90and1000and30": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.0) ) & (rec_higgs_pt>250)
    "ggF90and1000and35": (THWW>0.9) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    # check mjj and deta
    "VBF905and500and20": (THWW>0.905) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF905and1000and35": (THWW>0.905) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF905and500and20": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF905and1000and35": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF91and500and20": (THWW>0.91) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF91and1000and35": (THWW>0.91) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF91and500and20": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF91and1000and35": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF915and500and20": (THWW>0.915) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF915and1000and35": (THWW>0.915) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF915and500and20": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF915and1000and35": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF92and500and20": (THWW>0.92) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF92and1000and35": (THWW>0.92) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF92and500and20": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF92and1000and35": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF925and500and20": (THWW>0.925) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF925and1000and35": (THWW>0.925) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF925and500and20": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF925and1000and35": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF93and500and20": (THWW>0.93) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF93and1000and35": (THWW>0.93) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF93and500and20": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF93and1000and35": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF935and500and20": (THWW>0.935) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF935and1000and35": (THWW>0.935) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF935and500and20": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF935and1000and35": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF94and500and20": (THWW>0.94) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF94and1000and35": (THWW>0.94) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF94and500and20": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF94and1000and35": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF945and500and20": (THWW>0.945) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF945and1000and35": (THWW>0.945) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF945and500and20": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF945and1000and35": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)

    "VBF95and500and20": (THWW>0.95) & (n_bjets_T==0) & ( (mjj>500) & (deta>2.0) ) & (rec_higgs_pt>250)
    "VBF95and1000and35": (THWW>0.95) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggF95and500and20": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<500) | (deta<2.0) ) & (rec_higgs_pt>250)
    "ggF95and1000and35": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250)


    # ### ParT vs ParT-Finetuned (no VBF and ggF categorization)
    # "ParT9999": (fj_ParT_score>0.9999) & (n_bjets_T==0)
    # "ParT9995": (fj_ParT_score>0.9995) & (n_bjets_T==0)
    # "ParT999": (fj_ParT_score>0.999) & (n_bjets_T==0)
    # "ParT995": (fj_ParT_score>0.995) & (n_bjets_T==0)
    # "ParT99": (fj_ParT_score>0.99) & (n_bjets_T==0)
    # "ParT985": (fj_ParT_score>0.985) & (n_bjets_T==0)
    # "ParT98": (fj_ParT_score>0.98) & (n_bjets_T==0)
    # "ParT975": (fj_ParT_score>0.975) & (n_bjets_T==0)
    # "ParT97": (fj_ParT_score>0.97) & (n_bjets_T==0)
    # "ParT965": (fj_ParT_score>0.965) & (n_bjets_T==0)
    # "ParT96": (fj_ParT_score>0.96) & (n_bjets_T==0)
    # "ParT955": (fj_ParT_score>0.955) & (n_bjets_T==0)
    # "ParT95": (fj_ParT_score>0.95) & (n_bjets_T==0)
    # "ParT945": (fj_ParT_score>0.945) & (n_bjets_T==0)
    # "ParT94": (fj_ParT_score>0.94) & (n_bjets_T==0)

    # "THWW999": (THWW>0.999) & (n_bjets_T==0)
    # "THWW995": (THWW>0.995) & (n_bjets_T==0)
    # "THWW99": (THWW>0.99) & (n_bjets_T==0)
    # "THWW985": (THWW>0.985) & (n_bjets_T==0)
    # "THWW98": (THWW>0.98) & (n_bjets_T==0)
    # "THWW975": (THWW>0.975) & (n_bjets_T==0)
    # "THWW97": (THWW>0.97) & (n_bjets_T==0)
    # "THWW965": (THWW>0.965) & (n_bjets_T==0)
    # "THWW96": (THWW>0.96) & (n_bjets_T==0)
    # "THWW955": (THWW>0.955) & (n_bjets_T==0)
    # "THWW95": (THWW>0.95) & (n_bjets_T==0)
    # "THWW945": (THWW>0.945) & (n_bjets_T==0)
    # "THWW94": (THWW>0.94) & (n_bjets_T==0)
    # "THWW935": (THWW>0.935) & (n_bjets_T==0)
    # "THWW93": (THWW>0.93) & (n_bjets_T==0)
    # "THWW925": (THWW>0.925) & (n_bjets_T==0)
    # "THWW92": (THWW>0.92) & (n_bjets_T==0)
    # "THWW915": (THWW>0.915) & (n_bjets_T==0)
    # "THWW91": (THWW>0.91) & (n_bjets_T==0)
    # "THWW905": (THWW>0.905) & (n_bjets_T==0)
    # "THWW90": (THWW>0.90) & (n_bjets_T==0)

    # ### ggF all inclusive
    # "ggF95": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF945": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF94": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF935": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF93": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF925": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF92": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF915": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF91": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF905": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF90": (THWW>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF895": (THWW>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF89": (THWW>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF885": (THWW>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    # "ggF88": (THWW>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    # ### VBF all inclusive
    # "VBF92": (THWW>0.92) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF915": (THWW>0.915) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF91": (THWW>0.91) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF905": (THWW>0.905) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF90": (THWW>0.90) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF895": (THWW>0.895) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF89": (THWW>0.89) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF885": (THWW>885) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "VBF88": (THWW>88) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )

    # ### ggF pt bins
    # "ggF95pt250to350": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF95pt350to500": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF95pt500toInf": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF945pt250to350": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF945pt350to500": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF945pt500toInf": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF94pt250to350": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF94pt350to500": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>300) & (rec_higgs_pt<450)
    # "ggF94pt500toInf": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF935pt250to350": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF935pt350to500": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF935pt500toInf": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF93pt250to350": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF93pt350to500": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF93pt500toInf": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF925pt250to350": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF925pt350to500": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF925pt500toInf": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF92pt250to350": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF92pt350to500": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF92pt500toInf": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF915pt250to350": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF915pt350to500": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF915pt500toInf": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF91pt250to350": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF91pt350to500": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF91pt500toInf": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF905pt250to350": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF905pt350to500": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF905pt500toInf": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF90pt250to350": (THWW>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF90pt350to500": (THWW>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF90pt500toInf": (THWW>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF895pt250to350": (THWW>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF895pt350to500": (THWW>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF895pt500toInf": (THWW>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF89pt250to350": (THWW>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggF89pt350to500": (THWW>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggF89pt500toInf": (THWW>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF885pt250to350": (THWW>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt<300)
    # "ggF885pt350to500": (THWW>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>300) & (rec_higgs_pt<450)
    # "ggF885pt500toInf": (THWW>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "ggF88pt250to350": (THWW>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt<300)
    # "ggF88pt350to500": (THWW>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>300) & (rec_higgs_pt<450)
    # "ggF88pt500toInf": (THWW>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

samples_dir:
    "2018": ../eos/Oct10_hww_2018
    "2017": ../eos/Oct10_hww_2017
    "2016": ../eos/Oct10_hww_2016
    "2016APV": ../eos/Oct10_hww_2016APV

model_path: ../../weaver-core-dev/experiments_finetuning/v35_30/model.onnx
