samples:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - QCD
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - EWKvjets
    - WZQQorDYJets
    - Data

regions_sel:
    "VBF": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )

    "ggFpt250to300": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggFpt300to450": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggFpt450toInf": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "WJetsCR": (fj_ParT_score_finetuned>0.80) & (fj_ParT_score_finetuned<0.925) & (n_bjets_T==0)
    "TopCR": (fj_ParT_score_finetuned>0.80) & (n_bjets_T>0)


samples_dir:
    "2018": ../eos/Feb9_2018
    "2017": ../eos/Feb9_2017
    "2016APV": ../eos/Feb9_2016APV
    "2016": ../eos/Feb9_2016


model_path: ../../weaver-core-dev/experiments_finetuning/v35_26/model.onnx
