samples:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - QCD
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - EWKvjets
    - Data
    # - DYJets
    # - WZQQ
    - WZQQorDYJets

regions_massbins:
    "VBF92": 20
    "VBF915": 20
    "VBF91": 20
    "ggF975pt450toInf": 20

    "WJetsCR": 20
    "TopCR": 20


regions_sel:
    "VBF92": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF915": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF91": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF905": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF90": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF895": (fj_ParT_score_finetuned>0.89) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF89": (fj_ParT_score_finetuned>0.89) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF885": (fj_ParT_score_finetuned>0.885) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF88": (fj_ParT_score_finetuned>0.88) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF875": (fj_ParT_score_finetuned>0.875) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF87": (fj_ParT_score_finetuned>0.87) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF865": (fj_ParT_score_finetuned>0.865) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF86": (fj_ParT_score_finetuned>0.86) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF855": (fj_ParT_score_finetuned>0.855) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF85": (fj_ParT_score_finetuned>0.85) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )


    "ggF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF945": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF94": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF935": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF93": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF925": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF92": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF915": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF91": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF905": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF90": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    "ggF95pt250to300": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF95pt300to450": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF95pt450toInf": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF945pt250to300": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF945pt300to450": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF945pt450toInf": (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF94pt250to300": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF94pt300to450": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF94pt450toInf": (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF935pt250to300": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF935pt300to450": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF935pt450toInf": (fj_ParT_score_finetuned>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF93pt250to300": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF93pt300to450": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF93pt450toInf": (fj_ParT_score_finetuned>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF925pt250to300": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF925pt300to450": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF925pt450toInf": (fj_ParT_score_finetuned>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF92pt250to300": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF92pt300to450": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF92pt450toInf": (fj_ParT_score_finetuned>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF915pt250to300": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF915pt300to450": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF915pt450toInf": (fj_ParT_score_finetuned>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF91pt250to300": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF91pt300to450": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF91pt450toInf": (fj_ParT_score_finetuned>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF905pt250to300": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF905pt300to450": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF905pt450toInf": (fj_ParT_score_finetuned>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF90pt250to300": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF90pt300to450": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF90pt450toInf": (fj_ParT_score_finetuned>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)


    "WJetsCR": (fj_ParT_score_finetuned>0.50) & (fj_ParT_score_finetuned<0.85) & (n_bjets_T==0) & (met_pt>100)
    "TopCR": (fj_ParT_score_finetuned>0.50) & (n_bjets_T>0)



samples_dir:
    "2018": ../eos/Feb9_2018
    "2017": ../eos/Feb9_2017
    "2016APV": ../eos/Feb9_2016APV
    "2016": ../eos/Feb9_2016

# model_path: ../eos/model.onnx
model_path: ../eos/model_v35_12_14.onnx
