samples:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - QCD
    - DYJets
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - WZQQ
    - EWKvjets
    - Data

regions_sel:

    "ParTinclusive999": (fj_ParT_score>0.999) & (n_bjets_T==0)
    "ParTinclusive995": (fj_ParT_score>0.995) & (n_bjets_T==0)
    "ParTinclusive99": (fj_ParT_score>0.99) & (n_bjets_T==0)
    "ParTinclusive985": (fj_ParT_score>0.985) & (n_bjets_T==0)
    "ParTinclusive98": (fj_ParT_score>0.98) & (n_bjets_T==0)
    "ParTinclusive975": (fj_ParT_score>0.975) & (n_bjets_T==0)
    "ParTinclusive97": (fj_ParT_score>0.97) & (n_bjets_T==0)
    "ParTinclusive965": (fj_ParT_score>0.965) & (n_bjets_T==0)
    "ParTinclusive96": (fj_ParT_score>0.96) & (n_bjets_T==0)
    "ParTinclusive955": (fj_ParT_score>0.955) & (n_bjets_T==0)
    "ParTinclusive95": (fj_ParT_score>0.95) & (n_bjets_T==0)


    "inclusive985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0)
    "inclusive98": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0)
    "inclusive975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0)
    "inclusive97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0)
    "inclusive965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0)
    "inclusive96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0)
    "inclusive955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0)
    "inclusive95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0)


    ### VBF all inclusive
    "VBF985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF98": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )

    ### ggF all inclusive
    "ggF99": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF985": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF98": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF975": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF97": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF965": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF96": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF955": (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    ### ggF pt bins
    "ggF99pt250to300": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF99pt300to450": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF99pt450toInf": (fj_ParT_score_finetuned>0.99) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF985pt250to300": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF985pt300to450": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF985pt450toInf": (fj_ParT_score_finetuned>0.985) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF98pt250to300": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF98pt300to450": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF98pt450toInf": (fj_ParT_score_finetuned>0.98) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF975pt250to300": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF975pt300to450": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF975pt450toInf": (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF97pt250to300": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF97pt300to450": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF97pt450toInf": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF965pt250to300": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF965pt300to450": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF965pt450toInf": (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF96pt250to300": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF96pt300to450": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF96pt450toInf": (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)


    "ggF975to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF97to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF965to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF96to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF955to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF95to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF945to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF94to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    "ggF97to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF965to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF96to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF955to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF95to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF945to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF94to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )


    "ggF965to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF96to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF955to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF95to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF945to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF94to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    "ggF96to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF955to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF95to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF945to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF94to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )


    "SR975to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.975) & (n_bjets_T==0)
    "SR97to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0)
    "SR965to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0)
    "SR96to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0)
    "SR955to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0)
    "SR95to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0)
    "SR945to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0)
    "SR94to985": (fj_ParT_score_finetuned<0.985) & (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0)

    "SR97to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0)
    "SR965to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0)
    "SR96to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0)
    "SR955to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0)
    "SR95to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0)
    "SR945to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0)
    "SR94to98": (fj_ParT_score_finetuned<0.98) & (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0)


    "SR965to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.965) & (n_bjets_T==0)
    "SR96to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0)
    "SR955to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0)
    "SR95to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0)
    "SR945to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0)
    "SR94to975": (fj_ParT_score_finetuned<0.975) & (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0)

    "SR96to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.96) & (n_bjets_T==0)
    "SR955to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.955) & (n_bjets_T==0)
    "SR95to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0)
    "SR945to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.945) & (n_bjets_T==0)
    "SR94to97": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.94) & (n_bjets_T==0)



    # # put any "selection name: selection" here to store it in the templates
    # "SRVBF95": (fj_ParT_score_finetuned>0.95) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    # "SRggF97pt250to300": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>250) & (fj_pt<300)
    # "SRggF97pt300to450": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    # "SRggF97pt450toInf": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "WJetsCR97": (fj_ParT_score_finetuned>0.50) & (fj_ParT_score_finetuned<0.97) & (n_bjets_T==0)
    "WJetsCR96": (fj_ParT_score_finetuned>0.50) & (fj_ParT_score_finetuned<0.96) & (n_bjets_T==0)
    "WJetsCR95": (fj_ParT_score_finetuned>0.50) & (fj_ParT_score_finetuned<0.95) & (n_bjets_T==0)
    "WJetsCR94": (fj_ParT_score_finetuned>0.50) & (fj_ParT_score_finetuned<0.94) & (n_bjets_T==0)

    "TopCR": (fj_ParT_score_finetuned>0.50) & (n_bjets_T>0)

samples_dir:
    "2018": ../eos/Feb9_2018
    "2017": ../eos/Feb9_2017
    "2016APV": ../eos/Feb9_2016APV
    "2016": ../eos/Feb9_2016

model_path: ../eos/model.onnx
