samples:
    - ggF
    - VBF
    - WJetsLNu
    - TTbar
    - Data

regions_sel:

    "Pre-selection": (THWW>0.50) & (rec_higgs_pt>250)

    "VBF": (n_bjets_T==0) & (THWW>0.905) & ( (mjj>1000) & (deta>3.5) )
    "ggFpt250to300": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    "ggFpt300to450": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    "ggFpt450toInf": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    "WJetsCR": (n_bjets_T==0) & (THWW<0.905)
    "TopCR": (n_bjets_T>0)

samples_dir:
    "2018": ../eos/June25_hww_2018
    "2017": ../eos/June25_hww_2017
    "2016": ../eos/June25_hww_2016
    "2016APV": ../eos/June25_hww_2016APV

model_path: ../../weaver-core-dev/experiments_finetuning/v35_30/model.onnx
