############## FOR BUILDING `events_dict` PURPOSES

samples_dir:
    "2018": ../eos/Dec7_2018
    "2017": ../eos/Dec7_2017
    "2016APV": ../eos/Dec7_2016APV
    "2016": ../eos/Dec7_2016

samples:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

presel:
    ele:
        lep_fj_dr003: (lep_fj_dr>0.03)
        lep_fj_dr08: (lep_fj_dr<0.8)
        fj_pt250: (fj_pt>250)
        dphi<1.57: (abs_met_fj_dphi<1.57)
        MET>20: (met_pt>20)
        tagger>0.5: (fj_ParT_score_finetuned>0.5)
    mu:
        lep_fj_dr003: (lep_fj_dr>0.03)
        lep_fj_dr08: (lep_fj_dr<0.8)
        fj_pt250: (fj_pt>250)
        dphi<1.57: (abs_met_fj_dphi<1.57)
        MET>20: (met_pt>20)
        tagger>0.5: (fj_ParT_score_finetuned>0.5)

############## FOR PLOTTING PURPOSES
vars_to_plot:
    # - fj_minus_lep_m
    # - fj_bjets_ophem
    # - fj_bjets
    # - lep_met_mt
    # - ht
    # - met_fj_dphi
    # - deta
    # - met
    # - mjj
    - rec_higgs_m
    - rec_higgs_pt
    # - rec_dphi_WW
    # - fj_ParT_mass
    # - fj_ParticleNet_mass
    # - inclusive_score

    # - FirstFatjet_pt
    # - SecondFatjet_pt
    - fj_pt
    - lep_pt
    # - NumFatjets
    # - NumOtherJets
    - lep_fj_dr
    # - met_pt
    - met_fj_dphi
    - lep_met_mt
    - ht
    - fj_msoftdrop
    # - rec_W_qq_m
    # - rec_W_lnu_m
    # - fj_lsf3

samples_to_plot:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

channels_to_plot:
    - ele
    - mu

years_to_plot:
    - "2018"
    - "2017"
    - 2016APV
    - "2016"

regions_to_plot:
    Pre-selection: met_pt > 20
    Top CR: ( (fj_ParT_score_finetuned>0.5) & (n_bjets_T>0) )
    WJets CR: ( (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.50) & (n_bjets_T==0) & (met_pt>100) )

# plotting config
add_data: 1
logy: 0
add_soverb: 1
only_sig: False
mult: 100
