############## FOR BUILDING `events_dict` PURPOSES
samples:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson

presel:
    ele:
        lepton jet overlap: ( ( lep_fj_dr>0.03) )
    mu:
        lepton jet overlap: ( ( lep_fj_dr>0.03) )

sel:
    ele:
        tagger99: ( ( inclusive_score>0.99) )
        # tagger90: ( ( inclusive_score>0.9) )
        # taggerINV: ( ( inclusive_score<0.9) )

        # bT: ( ( n_bjets_T>0) )
        # bM: ( ( n_bjets_M>0) )

        # bT=: ( ( n_bjets_T==0) )
        # bM=: ( ( n_bjets_M==0) )

        lep_fj_dr: ( ( lep_fj_dr>0.5) )

    mu:
        tagger99: ( ( inclusive_score>0.99) )
        # tagger90: ( ( inclusive_score>0.9) )
        # taggerINV: ( ( inclusive_score<0.9) )

        # bT: ( ( n_bjets_T>0) )
        # bM: ( ( n_bjets_M>0) )

        # bT=: ( ( n_bjets_T==0) )
        # bM=: ( ( n_bjets_M==0) )

        lep_fj_dr: ( ( lep_fj_dr>0.5) )

weights:
    ele:
        weight_L1Prefiring: 1
        weight_genweight: 1
        weight_id_electron: 1
        weight_pileup: 1
        weight_reco_electron: 1
        weight_trigger_electron: 1
        weight_vjets_nominal: 1
    mu:
        weight_L1Prefiring: 1
        weight_genweight: 1
        weight_id_muon: 1
        weight_isolation_muon: 1
        weight_pileup: 1
        weight_trigger_iso_muon: 1
        weight_trigger_noniso_muon: 1
        weight_vjets_nominal: 1
