events_dict_path: "hists/v1/events_dict.pkl"

years_to_plot:
    # - "2018"
    - "2017"
    # - "2016"
    # - "2016APV"

channels_to_plot:
    - ele
    - mu

regions_to_plot:

    # "2016": met_pt > 20
    # "2016APV": met_pt > 20
    "2017": met_pt > 20
    # "2018": met_pt > 20



    # Pre-selection: met_pt > 20
    # Top CR: ( (THWW>0.75) & (n_bjets_T>0) )
    # WJets CR: ( (THWW<0.90) & (THWW>0.75) & (n_bjets_T==0) )
    # SR: ( (THWW>0.90) & (n_bjets_T==0) )    

samples_to_plot:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - Fake
    # - QCD
    - SingleTop
    - Diboson
    - EWKvjets
    - DYJets
    - WZQQ
    - TTbar
    - WJetsLNu
    - Data

vars_to_plot:
    - THWW
    - FirstFatjet_pt
    - SecondFatjet_pt
    - fj_pt
    - lep_pt
    - lep_fj_dr
    - lep_eta    
    - fj_lsf3
    - ht
    - lep_met_mt
    - met_fj_dphi
    - met_pt
    - met_phi
    - lep_met_mt
    - NumFatjets
    - NumOtherJets
    - rec_W_lnu_m
    - rec_W_qq_m
    - rec_higgs_m    
    - fj_ParT_mass
    - fj_mass        
    - lep_isolation_ele_highpt
    - lep_isolation_ele_lowpt
    - lep_isolation_mu_highpt
    - lep_isolation_mu_lowpt
    - lep_misolation_ele_highpt
    - lep_misolation_ele_lowpt
    - lep_misolation_mu_highpt
    - lep_misolation_mu_lowpt

outdir: "/Users/fmokhtar/Desktop/AN_2024/SYSTEMATICS/"

plot_syst_unc: True
plot_Fake_unc: 0.5

add_data: 1
add_soverb: True
logy: 0
legend_ncol: 2
mult: 1
massbin: 5
# blind_region: [90,160]
blind_region: False